In [14]:
import sys
sys.path.insert(1, '../../')

In [15]:
import pandas as pd

df = pd.read_csv("all_week.csv")
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2024-06-27T06:58:56.234Z,37.085300,-117.455700,1.4000,1.60,ml,24.0,163.37,0.114000,0.4062,...,2024-06-27T07:01:24.372Z,65 km WNW of Beatty Nevada,earthquake,NaN,5.300000,0.27,17.0,automatic,nn,nn
1,2024-06-27T06:44:54.810Z,38.843334,-122.833664,1.4600,1.19,md,9.0,122.00,0.004948,0.0100,...,2024-06-27T06:46:34.004Z,10 km WNW of Cobb CA,earthquake,0.44,0.660000,0.17,10.0,automatic,nc,nc
2,2024-06-27T06:37:15.170Z,19.379999,-155.248337,0.2600,2.19,ml,29.0,83.00,0.006159,0.1600,...,2024-06-27T06:39:54.080Z,7 km SSW of Volcano Hawaii,earthquake,0.17,0.140000,0.22,16.0,automatic,hv,hv
3,2024-06-27T06:23:40.209Z,31.677000,-104.394000,4.7006,1.60,ml,16.0,86.00,0.000000,0.2000,...,2024-06-27T06:40:06.187Z,55 km S of Whites City New Mexico,earthquake,0.00,1.424664,0.10,13.0,automatic,tx,tx
4,2024-06-27T05:40:55.548Z,31.549000,-104.012000,5.5752,1.50,ml,15.0,56.00,0.000000,0.3000,...,2024-06-27T06:15:46.061Z,33 km NW of Toyah Texas,earthquake,0.00,2.956069,0.20,11.0,automatic,tx,tx